### ISSUE TITLE
filter out short positions

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.portfolio.audit#58]
Broadly in-line with what was attempted here:
https://github.com/RMI-PACTA/PACTA_analysis/pull/533/files

Presumably it should happen here:
https://github.com/RMI-PACTA/pacta.portfolio.audit/blob/61f1472ff6930a905b0f31b8b9c5b8ebebefaf52/R/process_raw_portfolio.R#L46

@NAYRA-HERRERA has agreed that short positions should never be in the analysis at any point and should not appear in any of the outputs, so removing it as early on in the process as possible seems to be desirable.

**Comment by cjyetman** [comment]
Was this intentionally closed? @jdhoffa

**Comment by jdhoffa** [comment]
Yes, I realized we need _way_ more precise scoping before this is ready to be picked up.

Acceptance criteria scoping discussion is here:
https://dev.azure.com/RMI-PACTA/2DegreesInvesting/_workitems/edit/12306

Once we have a super clear idea of what needs to be done, I'll open a GH tracking issue
